FROM golang:1.21-alpine3.18 AS builder
WORKDIR /app
COPY . .
RUN go build -o sleuth

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/sleuth .
COPY configs ./configs

EXPOSE 8070
CMD ["/app/sleuth"]


